use_frameworks!

target 'CieloEcommerce_Example' do
  pod 'CieloEcommerce', :path => '../'

  target 'CieloEcommerce_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
  end
end
